python dpo.py \
    --dataset_name Joocjun/seahorse4dpo \
    --model_name_or_path bigscience/bloomz-1b7 \
    --learning_rate 5e-7 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --gradient_checkpointing \
    --logging_steps 25 \
    --eval_strategy no \
    --output_dir checkpoints/bloomz-1b7-seahorse4dpo \
    --no_remove_unused_columns \
    --bf16 true \
    --use_liger_kernel \
    --report_to wandb \
    --run_name bloomz-1b7-seahorse4dpo \
    --max_length 2048 \
